;;; emacs-pi-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from emacs-pi-core.el

(register-definition-prefixes "emacs-pi-core" '("emacs-pi--"))


;;; Generated autoloads from emacs-pi-history.el

(register-definition-prefixes "emacs-pi-history" '("emacs-pi-"))


;;; Generated autoloads from emacs-pi-rpc.el

(register-definition-prefixes "emacs-pi-rpc" '("emacs-pi-rpc-"))


;;; Generated autoloads from emacs-pi-session.el

(register-definition-prefixes "emacs-pi-session" '("emacs-pi-session-"))


;;; Generated autoloads from emacs-pi.el

(autoload 'emacs-pi-chat "emacs-pi"
"Choose a saved Pi session in ROOT, or start a new one.

(fn &optional ROOT)" t)
(autoload 'emacs-pi-new-session "emacs-pi"
"Start another Pi chat in the current chat's project." t)
(autoload 'emacs-pi-resume "emacs-pi"
"Choose a persisted Pi session from a detailed global list." t)
(autoload 'emacs-pi-switch-chat "emacs-pi"
"Switch among active emacs-pi chat buffers." t)
(register-definition-prefixes "emacs-pi" '("emacs-pi-"))


;;; Generated autoloads from emacs-pi-input.el

(register-definition-prefixes "emacs-pi-input" '("emacs-pi-"))


;;; Generated autoloads from emacs-pi-ui.el

(register-definition-prefixes "emacs-pi-ui" '("emacs-pi-"))


;;; End of scraped data

(provide 'emacs-pi-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; emacs-pi-autoloads.el ends here
